names:
- yellow
- red
- blue
nc: 3
path: ./
test: train_datasets/2-2 Our Aug+v8 Aug + Gussian/valid
train: train_datasets/2-2 Our Aug+v8 Aug + Gussian/train
val: train_datasets/2-2 Our Aug+v8 Aug + Gussian/valid
