names:
- yellow
- red
- blue
nc: 3
path: ./
test: train_datasets/3-4 v8 Aug + Gussian + Normalize/valid
train: train_datasets/3-4 v8 Aug + Gussian + Normalize/train
val: train_datasets/3-4 v8 Aug + Gussian + Normalize/valid
