names:
- yellow
- red
- blue
nc: 3
path: ./
test: new_train_datasets/new 2-2 Our Aug+v8 Aug + Gussian/valid
train: new_train_datasets/new 2-2 Our Aug+v8 Aug + Gussian/train
val: new_train_datasets/new 2-2 Our Aug+v8 Aug + Gussian/valid
