names:
- yellow
- red
- blue
nc: 3
path: ./
test: new_train_datasets/new 2-3 Our Aug+v8 Aug+ Normalize/valid
train: new_train_datasets/new 2-3 Our Aug+v8 Aug+ Normalize/train
val: new_train_datasets/new 2-3 Our Aug+v8 Aug+ Normalize/valid
