names:
- yellow
- red
- blue
nc: 3
test: ./datasets/3-4 v8 Aug + Gussian + Normalize/valid.txt
train: ./datasets/3-4 v8 Aug + Gussian + Normalize/train.txt
val: ./datasets/3-4 v8 Aug + Gussian + Normalize/valid.txt
