names:
- yellow
- red
- blue
nc: 3
test: ../datasets/new_train_datasets/new 2-3 Our Aug+v8 Aug+ Normalize/valid
train: ../datasets/new_train_datasets/new 2-3 Our Aug+v8 Aug+ Normalize/train
val: ../datasets/new_train_datasets/new 2-3 Our Aug+v8 Aug+ Normalize/valid